services:
  odoo:
    build: ./

    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - ./:/opt/odoo
      - odoo_data:/var/lib/odoo
    command: bash -c "$${PYTHON_PATH} $${DEBUG_ODOO} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "python3"
      DEBUG_ODOO: "-m debugpy --listen 0.0.0.0:8888"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/odoo.conf"
      ODOO_PARAM: ""
    depends_on:
      - postgres
    restart: unless-stopped
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./odoo_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - odoo
    restart: unless-stopped
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

volumes:
  odoo_data:
  postgres_data: