version: "3.9"

services:
  odoo:
    image: novobidevops/docker-base:odoo-17-v0.1.0
    # build: ./box

    # If developer want to use their own Docker environment, Do the following actions : 
    #
    # + comment line #9 
    # + uncomment line #10. 
    # + Make adjustment on file ./box/Dockerfile
    #
    # After docker-compose up, a new docker image will be built 
    # with the new adjustments on the file ./box/Dockerfile

    ports:
      - "8069:8069"
    volumes:
      - ./:/opt/odoo
      - odoo_data:/var/lib/odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "python3"
      START_ODOO: "/opt/odoo/odoo/odoo-bin -c /opt/odoo/odoo.conf"
      ODOO_PARAM: ""
    depends_on:
      - postgres
    restart: unless-stopped
    tty: true
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./box/odoo_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - odoo
    restart: unless-stopped
    tty: true
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true

volumes:
  odoo_data:
  postgres_data:
