FROM novobidevops/docker-base:odoo-17-v0.1.0

# Example 1: Install new python libs in the new image
# RUN pip3 install --no-cache-dir paramiko

# Example 2: Install new python libs from the requirement file
# USER root
# COPY requirements.txt /etc/requirements.txt
# RUN pip install --no-cache-dir -r /etc/requirements.txt
# RUN rm /etc/requirements.txt
# USER odoo