# Odoo 16 base
# version 1.1

ARG PYTHON_VERSION=3.9
ARG DEBIAN_RELEASE=bullseye

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_RELEASE}

ARG NODEJS_VERSION=18
ARG ODOO_VERSION=16

COPY packages /etc/packages
COPY odoo${ODOO_VERSION}-requirements.txt /etc/

RUN apt-get -qq update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		fontconfig \
		g++ \
		gcc \
		git \
		gnupg \
		libfreetype6 \
		libjpeg62-turbo \
		libpng16-16 \
		libx11-6 \
		libxcb1 \
		libxext6 \
		libxrender1 \
		locales \
		libldap2-dev \
		libsasl2-dev \
		libpq-dev \
		vim \
		xfonts-75dpi \
		xfonts-base \
# install wkhtmltopdf
	&& dpkg -i /etc/packages/*.deb \
# setting locale
	&& sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
	&& locale-gen \
# install postgresql-client
	&& curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/pgdg.gpg \
	&& echo 'deb [signed-by=/etc/apt/trusted.gpg.d/pgdg.gpg] https://apt.postgresql.org/pub/repos/apt bullseye-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
	&& apt-get -qq update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		postgresql-client \
# install nodejs
	&& curl -sSL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash - \
	&& apt-get install -y --no-install-recommends nodejs \
	&& npm update --global \
	&& npm install --global --silent postcss rtlcss less less-plugin-clean-css \
# install python3 libs
	&& pip3 install --no-cache-dir --upgrade pip \
	&& pip3 install --no-cache-dir --upgrade setuptools wheel \
	&& pip3 install --no-cache-dir \
		asn1crypto \ 
        coverage \ 
        dbfread \ 
        debugpy \ 
        google_auth \ 
        mock \
        pdfminer \ 
        phonenumbers \ 
        redis \ 
        slugify \ 
        watchdog \
	&& pip3 install --no-cache-dir -r /etc/odoo${ODOO_VERSION}-requirements.txt \
# clean
	&& apt-get remove -y lsb-release gnupg curl gcc g++ \
	&& apt-get autoremove -y \
	&& apt-get clean \
	&& rm -rf /etc/packages/*.deb /var/lib/apt/lists/* /etc/apt/sources.list.d/pgdg.list /etc/apt/trusted.gpg.d/pgdg.gpg /etc/odoo${ODOO_VERSION}-requirements.txt

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en